FuelApp/Fuel/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'Fuel'
urlpatterns = [
    path('', index, name='index'),
    path('login/', LoginFormView.as_view(), name='login'),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),
    path('change-status/', change_status, name='change_status'),
    path('agent-page/', agent_page, name='agent_page'),
    path('mission-complete/', mission_complete, name='mission-complete'),
    re_path(r'check-request-assigned/',
            check_request_assigned, name='check-request-assigned'),
    path('dashboard/', RequestFuelFormView.as_view(), name='dashboard'),
    re_path(r'check-agent-available/',
            check_fuel_request_assigned, name='check-agent-available'),
    path('map/', show_map, name="map"),
]


FuelApp/FuelApp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Fuel.urls'))
]

FuelApp/Fuel/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from django.db import models
from django.urls import reverse
from .managers import UserManager
from django.utils.translation import gettext_lazy as _


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=200)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    car_licence = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=15)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    ip_address = models.CharField(max_length=20, null=True)

    class Role(models.TextChoices):
        AGENT = 'a', _('Agent')
        USER = 'u', _('User')
        SUPERVISOR = 's', _('Supervisor')

    role = models.CharField(
        max_length=2,
        choices=Role.choices,
        default=Role.USER,
    )

    class StatusTypes(models.TextChoices):
        AVAILABLE = 'av', _('Available')
        UNAVAILABLE = 'un', _('Unavailable')
        OCCUPIED = 'oc', _('Occupied')

    status = models.CharField(
        max_length=2,
        choices=StatusTypes.choices,
        default=StatusTypes.AVAILABLE,
    )
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return reverse('Fuel:login')

    def __str__(self):
        return str(self.username) + " - " + str(self.role)

    def __eq__(self, __o: object) -> bool:
        if __o:
            return self.username == __o.username
        return False


class FuelRequest(models.Model):
    class Status(models.TextChoices):
        LOOKING_FOR_AGENT = 'looking_for_agent'
        IN_PROGRESS = 'in_progress'
        SUCCESSFUL = 'successful'

    created_at = models.DateTimeField(auto_now_add=True)
    supervisor = models.ForeignKey(
        User, null=True, on_delete=models.CASCADE, related_name='supervisor_nazer')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, unique=False, related_name='requesting_user')
    agent = models.ForeignKey(User, null=True, blank=True,
                              on_delete=models.CASCADE, related_name='driver_agent')
    status = models.CharField(
        max_length=25, choices=Status.choices, default=Status.LOOKING_FOR_AGENT)
    address = models.CharField(max_length=200, default="")
    amount = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user.username) + ' - ' + str(self.created_at)

FuelApp/Fuel/forms.py
from django import forms

from Fuel.models import FuelRequest, User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class RegisterForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    car_licence = forms.CharField()
    phone_number = forms.CharField()
    role = forms.ChoiceField(choices=User.Role.choices)


class RequestFuelForm(forms.Form):
    amount = forms.IntegerField(max_value=40)


class AssignFuelRequstForm(forms.ModelForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self._set_agent_choices()

    def _set_agent_choices(self):
        self.fields['agent'].choices = sorted([
            (agent.id, f"{agent.first_name} {agent.last_name}") for agent in
            User.objects.all().filter(role=User.Role.AGENT, status=User.StatusTypes.AVAILABLE)
        ])

    class Meta:
        model = FuelRequest
        fields = [
            "amount",
            "address",
            "agent",
        ]
        widgets = {
            "amount": forms.NumberInput(attrs={'readonly': 'readonly'}),
            "address": forms.TextInput(attrs={'readonly': 'readonly'}),
        }

FuelApp/Fuel/views.py
import time

from django.contrib.auth.models import Group
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import requests
import folium
from django.contrib import messages

from .models import User, FuelRequest
from .forms import LoginForm, RegisterForm, RequestFuelForm
from .utils import *


def index(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        if request.user.role == User.Role.AGENT:
            return agent_page(request)
        elif request.user.role == User.Role.SUPERVISOR:
            redirect('admin:index')
        return redirect('Fuel:dashboard')
    return render(request, 'index.html')


def visitor_ip_address(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class LoginFormView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = 'Fuel:index'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(self.request, username=username, password=password)
        if user:
            if user.role == User.Role.AGENT:
                login(self.request, user)
                return redirect("Fuel:agent_page")

            elif user.role == User.Role.SUPERVISOR:
                login(self.request, user)
                return redirect("admin:index")

            login(self.request, user)
            return redirect('Fuel:dashboard')
        else:
            return render(self.request, "index.html", {"error": True, "login_error": True})


class RequestFuelFormView(FormView):
    template_name = 'dashboard.html'
    form_class = RequestFuelForm
    success_url = 'Fuel:dashboard'

    def form_valid(self, form):
        address = requests.get('https://api.ipify.org').content.decode('utf8')
        amount = form.cleaned_data['amount']
        fuel_request = FuelRequest(address=address, amount=amount,
                                   user=User.objects.get(username=self.request.user.username))
        fuel_request.save()
        return redirect("Fuel:dashboard")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        fuel_request = FuelRequest.objects.filter(
            user=self.request.user).exclude(status=FuelRequest.Status.SUCCESSFUL)
        assert len(fuel_request) in [1, 0]

        if len(fuel_request) == 0:
            context_data.update(
                {'no_open_request': True, 'request_assigned': False})
            return context_data

        fuel_request = fuel_request[0]
        if fuel_request.status == FuelRequest.Status.LOOKING_FOR_AGENT:
            context_data.update(
                {'no_open_request': False, 'request_assigned': False})
            return context_data
        context_data.update(
            {'no_open_request': False, 'request_assigned': True, 'agent_first_name': fuel_request.agent.first_name,
             'agent_last_name': fuel_request.agent.last_name, 'agent_car_licence': fuel_request.agent.car_licence,
             'agent_phone_number': fuel_request.agent.phone_number})
        return context_data


class RegisterFormView(FormView):
    template_name = 'register.html'
    form_class = RegisterForm
    success_url = 'Fuel:login'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        car_licence = form.cleaned_data['car_licence']
        phone_number = form.cleaned_data['phone_number']
        role = form.cleaned_data['role']
        users = User.objects.filter(username=username)
        ip_address = requests.get('https://api.ipify.org').content.decode('utf8')

        if users:
            return render(self.request, "index.html", {"error": True, "username_unavailable": True})
        user = User(username=username, first_name=first_name, last_name=last_name, password=password,
                    car_licence=car_licence, phone_number=phone_number, ip_address=ip_address)
        user.set_password(password)
        user.role = role
        user.save()
        if user.role == User.Role.SUPERVISOR:
            Group.objects.get(name='supervisor').user_set.add(user)
        return redirect('Fuel:login')


@login_required
def agent_page(request):
    temp = User.objects.all().filter(username=request.user.username)
    if temp:
        if temp[0].status == User.StatusTypes.UNAVAILABLE:  # agent is unavailable
            return render(request, "agent.html", {'status': temp[0].status})

        fuel_request = FuelRequest.objects.filter(
            agent=temp[0], status=FuelRequest.Status.IN_PROGRESS)
        assert len(fuel_request) in [1, 0]
        if len(fuel_request) == 0:  # no fuel request assigned to agent
            return render(request, "agent.html", {'status': temp[0].status})

        else:  # a request is assigned to agent, his status becomes occupied
            temp[0].status = User.StatusTypes.OCCUPIED
            temp[0].save()
            fuel_request = fuel_request[0]
            response_data = {'status': temp[0].status}
            response_data['user_phone_number'] = fuel_request.user.phone_number
            response_data['user_first_name'] = fuel_request.user.first_name
            response_data['user_last_name'] = fuel_request.user.last_name
            response_data['user_address'] = fuel_request.address
            response_data['user_amount'] = fuel_request.amount
            response_data['user_car_licence'] = fuel_request.user.car_licence
            return render(request, "agent.html", response_data)

    return logout_user(request)


@login_required
def logout_user(request):
    logout(request)
    return redirect('Fuel:index')


@login_required
def change_status(request):
    users = User.objects.all().filter(username=request.user.username)
    if users:
        user = users[0]
        if user.status == User.StatusTypes.AVAILABLE:
            user.status = User.StatusTypes.UNAVAILABLE
        elif user.status == User.StatusTypes.UNAVAILABLE:
            user.status = User.StatusTypes.AVAILABLE
        user.save()
        return redirect("Fuel:agent_page")

    return logout_user(request)


@login_required
def mission_complete(request):
    users = User.objects.all().filter(username=request.user.username)
    if users:
        fuel_request = FuelRequest.objects.filter(
            agent=users[0], status=FuelRequest.Status.IN_PROGRESS)
        assert len(fuel_request) in [1, 0]

        if len(fuel_request) == 0:
            return redirect("Fuel:agent_page")
        else:
            fuel_request = fuel_request[0]
            fuel_request.status = FuelRequest.Status.SUCCESSFUL
            fuel_request.save()
            users[0].status = User.StatusTypes.AVAILABLE
            users[0].save()
            return redirect("Fuel:agent_page")

    return logout_user(request)


@login_required
def check_request_assigned(request):
    fuel_request = FuelRequest.objects.filter(
        agent=request.user).exclude(status=FuelRequest.Status.SUCCESSFUL)
    assert len(fuel_request) in [1, 0]
    if len(fuel_request) == 0:
        return HttpResponse("")

    fuel_request = fuel_request[0]
    assert fuel_request.status == FuelRequest.Status.IN_PROGRESS
    return HttpResponse('assigned')


@login_required
def check_fuel_request_assigned(request):
    fuel_request = FuelRequest.objects.filter(
        user=request.user).exclude(status=FuelRequest.Status.SUCCESSFUL)
    assert len(fuel_request) in [1, 0]
    if len(fuel_request) == 0:
        return HttpResponse("")

    fuel_request = fuel_request[0]
    if fuel_request.status == FuelRequest.Status.LOOKING_FOR_AGENT:
        return HttpResponse("")
    return HttpResponse('assigned')


def show_map(request):
    ips = []
    user = request.user
    role = user.role
    message = 'No IP address exists'
    colors = []
    if role == User.Role.AGENT:
        all_fuels = FuelRequest.objects.all()
        for fuels in all_fuels:
            if (fuels.agent == user) and (fuels.address not in ips):
                ips.append([fuels.address, 'Order'])
                colors.append('red')
        message = 'No fuel request exists'
    elif user.is_superuser:
        all_fuels = FuelRequest.objects.all()
        for fuels in all_fuels:
            if fuels.status != FuelRequest.Status.SUCCESSFUL and fuels.address not in ips:
                ips.append([fuels.address, 'Order'])
                color = 'blue' if fuels.status == FuelRequest.Status.LOOKING_FOR_AGENT else 'green'
                colors.append(color)
        all_users = User.objects.all()
        for user in all_users:
            if user.role == User.Role.AGENT and user.status == User.StatusTypes.AVAILABLE:
                if user.ip_address not in ips:
                    ips.append([user.ip_address, 'Agent'])
    elif role == User.Role.USER:
        return redirect('Fuel:dashboard')

    try:
        locations = []
        for ip in ips:
            ipDict = {}
            ipDict['query'] = ip[0]
            locations.append(ipDict)
        response = requests.post("http://ip-api.com/batch", json=locations).json()
        points = []
        for i in range(len(response)):

FuelApp/Fuel/templates/agent.html
{% extends 'base.html' %}
{% block title %}
Agent Page
{% endblock %}
{% block body %}
<div class="container">
    <div id="status" class="row my-flex">
        <div class="col s6">
            {% csrf_token %}
            <h3>
                Your status is:
                {% if status == 'av' %}
                <div class="my-red">Available</div>
                {% elif status == 'un' %}
                <div class="my-red">Unavailable</div>
                {% else %}
                <div class="my-red">Occupied</div>
                {% endif %}
            </h3>

            {% if status == 'oc' %}
            <b> new Mission Available! </b> <br>
            <b> Customer Information </b> <br>
            first name: {{ user_first_name }} <br>
            last name: {{ user_last_name }} <br>
            car licence: {{ user_car_licence }} <br>
            phone number: {{ user_phone_number }} <br>
            address: {{ user_address }} <br>
            amount: {{ user_amount }} <br>
            <a onClick="done" class="waves-effect waves-light btn col s12" href="/mission-complete">Done</a>
            {% endif %}
        </div>

    </div>
    <div class="col s3 offset-s3">
        {% if status != 'oc' %}
        <a class="waves-effect waves-light btn" href="/change-status">
            change your status
        </a>
        {% endif %}
    </div>

</div>
<style>
    .my-flex {
        display: flex;
        align-items: center;
    }

    .my-red {
        color: red;
    }
</style>
<script>
    $(document).ready(function () {
        var myInterval;
        var previous_result;
        $.ajax({
            url: "check-request-assigned/",
            success: function (result) {
                if (result !== null) {
                    previous_result = result;
                }
            },
            error: function (result) {
                // alert('error');
            }
        });
        myInterval = setInterval(waitForDriver, 1000);
        function waitForDriver() {
            $.ajax({
                url: "check-request-assigned/",
                success: function (result) {
                    if (result !== null && result !== previous_result) {
                        location.reload();
                    }
                },
                error: function (result) {
                    // alert('error');
                }
            });
        }
    });
</script>

{% endblock %}

FuelApp/Fuel/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <style>
        .rtl {
            direction: rtl;
        }
    </style>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    <nav class="blue darken-2">
        <div class="nav-wrapper row">
            <div id="navbar">
                <div class="col s5">
                    <ul class="left">
                        {% if request.user.is_authenticated %}
                        <li><a id="logout" href="{% url 'Fuel:logout' %}"><i
                                    class="material-icons left">logout</i>Logout</a></li>
                        <li><a id="map" href="{% url 'Fuel:map' %}"><i
                                    class="material-icons left">map</i>map</a></li>
                        {% else %}
                        <li><a id="login" href="{% url 'Fuel:login' %}"><i
                                    class="material-icons left">login</i>Login</a></li>
                        <li><a id="register" href="{% url 'Fuel:register' %}"><i
                                    class="material-icons left">add</i>Register</a></li>
                        {% endif %}
                        <li><a id="homepage" href="{% url 'Fuel:index' %}"><i
                                    class="material-icons left">home</i>Homepage</a></li>
                    </ul>
                </div>
                <div class="col s7">
                    <ul class="right">
                        <li><i class="material-icons right">local_gas_station</i></li>
                        <li>Welcome to Fuel App</li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
</body>

</html>

FuelApp/Fuel/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}
DashBoard
{% endblock %}
{% block body %}
<div class="container">
    <div class="row card-panel s12">
        <div class="container">
            <form class="col s12 align-center" method="post">
                {% csrf_token %}

                {% if no_open_request %}
                {{ form.as_p }}
                <button class="btn waves-effect waves-light" type="submit" name="action">Request Fuel</button>

                {% if error %}
                <div id="error">
                    something went wrong!
                </div>
                {% endif %}

                {% elif request_assigned %}
                <b> a delivery agent is coming to you! </b> <br>
                first name: {{ agent_first_name }} <br>
                last name: {{ agent_last_name }} <br>
                car licence: {{ agent_car_licence }} <br>
                phone number: {{ agent_phone_number }} <br>

                {% if error %}
                <div id="error">
                    something went wrong!
                </div>
                {% endif %}

                {% else %}
                <b> your request successfully sent to server.
                    we are processing your request.
                    this page would refresh automatically when a delivery agent found for you.
                </b>

                {% if error %}
                <div id="error">
                    something went wrong!
                </div>
                {% endif %}
                {% endif %}
            </form>
        </div>
    </div>
</div>

<center>
     <img src="https://s20.picofile.com/file/8445260476/fuel.jpg" alt="Fuel App" width="750" height="500">
</center>

<script>
    $(document).ready(function () {
        var myInterval;
        var previous_result;
        $.ajax({
            url: "check-agent-available/",
            success: function (result) {
                if (result !== null) {
                    previous_result = result;
                }
            },
            error: function (result) {
                // alert('error');
            }
        });
        myInterval = setInterval(waitForDriver, 1000);
        function waitForDriver() {
            $.ajax({
                url: "check-agent-available/",
                success: function (result) {
                    if (result !== null && result !== previous_result) {
                        location.reload();
                    }
                },
                error: function (result) {
                    // alert('error');
                }
            });
        }
    });
</script>

{% endblock %}

FuelApp/Fuel/templates/index.html
{% extends 'base.html' %}
{% block title %}
Home Page
{% endblock %}
{% block body %}

{% if error %}
<div class="container">
    <div class="row card-panel s12">
        <div class="container">
            <form class="col s12 align-center" method="post">
                <div class="">
                    {% if username_unavailable %}
                    <div>Username is not available</div>
                    {% endif %}
                    {% if login_error %}
                    <div>Username or Password incorrect</div>
                    {% endif %}
                    {% if map_error %}
                    <div>{{ message }}</div>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}

<center>
     <img src="https://s20.picofile.com/file/8445260476/fuel.jpg" alt="Fuel App" width="750" height="500">
</center>

{% endblock %}

FuelApp/Fuel/templates/login.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock %}
{% block body %}
<div class="container">
    <div class="row card-panel s12">
        <div class="container">
            <form class="col s12 align-center" method="post">
                <div class="">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button class="btn waves-effect waves-light" type="submit" name="action">Login</button>
                {% if error %}
                <div id="error">
                    username or password is wrong
                </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

FuelApp/Fuel/templates/map.html
{% extends 'base.html' %}
{% block title %}
map
{% endblock %}
{% block body %}
<div class="container">
    <div class="row card-panel s12">
        <div class="container">
            {% if error %}
                <div id="error">
                    {{message}}
                </div>
            {% else %}
                <div class="">
                    {{ map|safe }}
                </div>
            {% endif %}
        </div>
    </div>
</div>

{% if error %}
    <center>
        <img src="https://s20.picofile.com/file/8445260476/fuel.jpg" alt="Fuel App" width="750" height="500">
    </center>
{% endif %}
{% endblock %}

FuelApp/Fuel/templates/register.html
{% extends 'base.html' %}
{% block title %}
Register
{% endblock %}
{% block body %}
<div class="container">
    <div class="row card-panel s12">
        <div class="container">
            <form class="col s10" method="post">
                <div class="">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button class="btn waves-effect waves-light" type="submit" name="action">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}